#!/bin/sh
#
infoFile="LetsGetCheckedApp/Info.plist"
branchName=`git branch --list | grep "\*" | awk '{print $2}'`
branch=${1:-$branchName}
buildNumber=$(expr $(git rev-list $branch --count) - $(git rev-list HEAD..$branch --count) + 1)
echo "Updating build number to $buildNumber using branch '$branch'."
/usr/libexec/PlistBuddy -c "Set :CFBundleVersion $buildNumber" $infoFile
git add --verbose $infoFile
